### ISSUE TITLE
how to generate "sei_patch.npy" from the full 3d data?

### ISSUE THREAD

**Issue by leocd91** [yxycug/Seismic-Facies-classification#2]
What shape is the **sei_patch.npy** ?
Is it depth x width x sample number?

**Comment by yxycug** [comment]
yes, 256 depth × 256 width




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yxycug/Seismic-Facies-classification"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 上午10:05
收件人:&nbsp;"yxycug/Seismic-Facies-classification"<Seismic-Facies-classification@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yxycug/Seismic-Facies-classification] how to generate "sei_patch.npy" from the full 3d data? (#2)





 
What shape is the sei_patch.npy ?
 Is it depth x width x sample number?

**Comment by leocd91** [comment]
thanks.
can you share the code on how you split the patch? any overlap?
I'm trying to reproduce your result

**Comment by leocd91** [comment]
thanks.
can you share the code on how you split the patch train data? any overlap?
I'm trying to reproduce your result

**Comment by yxycug** [comment]
U can use the simplest iteration to split the patch,such as:
n=0
for&nbsp;i&nbsp;in&nbsp;range(aaa):
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;j&nbsp;in&nbsp;range(bbb):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;k&nbsp;in&nbsp;range(ccc):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;X=seismic[64*i:64*i+128,64*j:64*j+128,64*k:64*k+128]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Y=label[64*i:64*i+128,64*j:64*j+128,64*k:64*k+128]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;X.tofile(newdpath+str(n)+".dat",format="%4")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Y.tofile(newfpath+str(n)+".dat",format="%4")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n+=1
u can also choose&nbsp;variable&nbsp;overlaps and do some flip&nbsp;vertical to augment training data





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "leocd91"<notifications@github.com&gt;; 
发送时间: 2020年11月17日(星期二) 下午4:29
收件人: "yxycug/Seismic-Facies-classification"<Seismic-Facies-classification@noreply.github.com&gt;; 
抄送: "Dionysus"<378065101@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [yxycug/Seismic-Facies-classification] how to generate &quot;sei_patch.npy&quot; from the full 3d data? (#2)





 
thanks.
 can you share the code on how you split the patch? any overlap?
 I'm trying to reproduce your result

**Comment by leocd91** [comment]
```
     54         up_6 = self.up6(c5)
---> 55         merge6 = torch.cat([up_6,c4],dim=1)
     56         c6 = self.conv6(merge6)
     57         up_7 = self.up7(c6)

RuntimeError: Sizes of tensors must match except in dimension 2. Got 31 and 30 (The offending index is 0)
```
Seems error on the upscaling part on unet..

**Comment by yxycug** [comment]
i run the code just now, and found nothing wrong. plz check the dimension of ur input data




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "leocd91"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 下午4:44
收件人: "yxycug/Seismic-Facies-classification"<Seismic-Facies-classification@noreply.github.com&gt;; 
抄送: "Dionysus"<378065101@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [yxycug/Seismic-Facies-classification] how to generate &quot;sei_patch.npy&quot; from the full 3d data? (#2)





      54         up_6 = self.up6(c5) ---&gt; 55         merge6 = torch.cat([up_6,c4],dim=1)      56         c6 = self.conv6(merge6)      57         up_7 = self.up7(c6) RuntimeError: Sizes of tensors must match except in dimension 2. Got 31 and 30 (The offending index is 0)  
Seems error on the upscaling part on unet..

**Comment by leocd91** [comment]
the shape is (256,256,number_of_sample)
is it right?

**Comment by yxycug** [comment]
plz&nbsp;permute (number_of_sample,256,256)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "leocd91"<notifications@github.com&gt;; 
发送时间: 2020年11月19日(星期四) 上午10:39
收件人: "yxycug/Seismic-Facies-classification"<Seismic-Facies-classification@noreply.github.com&gt;; 
抄送: "Dionysus"<378065101@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [yxycug/Seismic-Facies-classification] how to generate &quot;sei_patch.npy&quot; from the full 3d data? (#2)





 
the shape is (256,256,number_of_sample)

**Comment by leocd91** [comment]
nice, it's working now.. thanks.
